version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: apis/Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_SECRET: ${APP_SECRET}
      DEFAULT_URI: ${DEFAULT_URI}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - notas

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www/html:ro
      - ../apis:/var/www/api:ro
      - ./nginx:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - notas

  db:
    image: mariadb:10.11.7
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - notas

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: ["/bin/sh", "-c", "trap exit TERM; while :; do sleep 12h & wait $${!}; done;"]

volumes:
  db_data:

networks:
  notas:
    driver: bridge
