services:
  api:
    build:
      context: ..
      dockerfile: apis/Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_SECRET: ${APP_SECRET}
      DEFAULT_URI: ${DEFAULT_URI}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - notas

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      - api
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ../:/var/www/html:ro
      - ../apis:/var/www/api:ro
      - ./nginx/notas.local.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - notas

  db:
    image: mariadb:10.11.7
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - notas

volumes:
  db_data:

networks:
  notas:
    driver: bridge
